---
# https://taskfile.dev

version: '3'

tasks:
  fmt:
    silent: true
    cmds:
      - ./gradlew ktlintFormat

  build:
    silent: true
    cmds:
      - ./gradlew build

  installDebug:
    silent: true
    cmds:
      - ./gradlew installDebug
